version: "3"
services:
  employee-jdbc:
    image: spring-boot
    ports:
      - "8081:8080"
    networks:
      - planing-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - planing-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=planing  

networks:
  planing-mysql: 