name: DevOps Test


on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master

  # Schedule the job to everyday to refresh dynamic first page
  schedule:
    - cron: '0 0 * * *'

jobs:

  rendering:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: clean with Maven
        run: mvn clean
      - name: Build with Maven
        run: mvn install
      - name: Deploy to GitHub jar 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: build
          folder: target
      - name: Commit and Push new README.md to the repository
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


 